schedules:
- cron: "0 7 * * SUN"
  displayName: Weekly Sunday
  branches:
    include:
    - master
  always: true

jobs:
- job: Linux
  timeoutInMinutes: 90
  pool:
    vmImage: 'ubuntu-20.04'
  container: ros:foxy
  steps:
  - script: |
      printenv
        echo hello
        pwd
        ls
    displayName: filesystem check
  - script: |
        cd $(Agent.BuildDirectory)
        ./rmw_build/create_workspace.sh
    displayName: repos setup
  - script: |
        cd $(Agent.BuildDirectory)
        ./rmw_build/build_all.sh
    displayName:  environment setup and build
