schedules:
- cron: "0 7 * * SUN"
  displayName: Weekly Sunday
  branches:
    include:
    - master
  always: true

jobs:
- job: Linux
  timeoutInMinutes: 90
  pool:
    vmImage: 'ubuntu-18.04'
  container: adamsjoci/opendds_ros2_docker:latest
  steps:
  - script: |
      printenv
        echo hello
        pwd
        ls
    displayName: filesystem check
  - script: |
        mkdir src
        vcs import src < ros2.repos        
    displayName: repos setup
  - script: |
        ./build_all.sh        
    displayName:  environment setup and build
