schedules:
- cron: "0 7 * * SUN"
  displayName: Weekly Sunday
  branches:
    include:
    - master
  always: true

jobs:
- job: Linux
  timeoutInMinutes: 90
  pool:
    vmImage: 'ubuntu-20.04'
  container: objectcomputing/opendds_ros2:latest
  steps:
  - checkout: self  # self represents the repo where the initial Azure Pipelines YAML file was found
    clean: true
    path: ws/rmw_build
  - script: |
      printenv
        echo hello
        pwd
        ls
    displayName: filesystem check
  - script: |
        cd $(Agent.BuildDirectory)/ws
        ./rmw_build/create_workspace.sh
    displayName: repos setup
  - script: |
        cd $(Agent.BuildDirectory)/ws
        ./rmw_build/build_all.sh
    displayName:  environment setup and build
